# ──────────────────────────────────────────────────────────────
# Usage (from DHIRL_bridge root):
#   python -m src_autotest.run src_autotest/configs/test_bridge.yaml --groups projection_width
# ──────────────────────────────────────────────────────────────

# We test dinov2, watch curve of states increase, test 32 actions
defaults:
  num_states: 512
  num_actions: 32
  data_dir: data_autotest/trajs

  ll_filename: ll.csv
  output_dir: src_autotest/outputs
  discount: 0.97
  num_repeats: 1
  num_latents: 3
  rand_seed: 42

  model_type: IntentionRNN
  hidden_dim: 128
  rnn_hidden_dim: 128
  num_layers: 1
  dropout: 0.2
  nhead: 4
  lr: 0.001

  reg_type: l1
  reg_weight: 0.0

  num_epochs: 1
  loss_threshold: 1e-3
  max_iterations: 150


groups:
  intention_num:
    id: G01
    description: "All NS = 512 data cases from data_autotest/trajs, test intention num 1 - 6"
    experiments:
      - id: E01
        data_dir: data_autotest/trajs
        num_latents: 1
      - id: E02
        data_dir: data_autotest/trajs
        num_latents: 2
      - id: E03
        data_dir: data_autotest/trajs
        num_latents: 3
      - id: E04
        data_dir: data_autotest/trajs
        num_latents: 4
      - id: E05
        data_dir: data_autotest/trajs
        num_latents: 5
      - id: E06
        data_dir: data_autotest/trajs
        num_latents: 6

  3072states-autotest:
    id: G02
    description: "All NS = 3072 data cases from data_autotest/trajs"
    experiments:
      - id: E01
        data_dir: data_autotest/trajs
        num_states: 3072
        num_actions: 32
      - id: E02
        data_dir: data_autotest/dinov2_small
        num_states: 3072
        num_actions: 32
      - id: E03
        data_dir: data_autotest/dinov2_base
        num_states: 3072
        num_actions: 32
      - id: E04
        data_dir: data_autotest/dinov2_large
        num_states: 3072
        num_actions: 32
      - id: E05
        data_dir: data_autotest/dinov2_giant
        num_states: 3072
        num_actions: 32

  # 512states48actions-autotest:
  #   id: G03
  #   description: "All NS = 512 data cases from data_autotest/trajs"
  #   experiments:
  #     - id: E01
  #       data_dir: data_autotest/trajs
  #       num_states: 512
  #       num_actions: 48
  #     - id: E02
  #       data_dir: data_autotest/dinov2_small
  #       num_states: 512
  #       num_actions: 48
  #     - id: E03
  #       data_dir: data_autotest/dinov2_base
  #       num_states: 512
  #       num_actions: 48
  #     - id: E04
  #       data_dir: data_autotest/dinov2_large
  #       num_states: 512
  #       num_actions: 48
  #     - id: E05
  #       data_dir: data_autotest/dinov2_giant
  #       num_states: 512
  #       num_actions: 48